[ollama]
url = "http://localhost:11434"
embedding_model = "nomic-embed-text"

[qdrant]
url = "http://localhost:6334"
collection_name = "code_search"
vector_size = 768
num_results = 5

[chunking]
chunk_size_range = [1, 2048]
supported_filetypes = [
"rs",
"py",
"js",
"ts",
"go",
"c",
"h",
"cpp",
"cc",
"cxx",
"c++",
"java",
"rb",
"md",
"nix",
"html",
"php",
"txt",
]
